### ISSUE TITLE
Elasticsearch improvements

### ISSUE THREAD

**Issue by pgrill** [pln-fing-udelar/covid19-qa#12]
Hacer que Elasticsearch siempre devuelva al menos `batch_size` fragmentos (aunque el tamaño de lo que se procesa no es el mismo que el fragmento; capaz determinar un número en función del `batch_size` tipo la mitad, o para llegar a un número de batches estimado dado). Capaz el container puede consumir la env var del docker-compose que ya se usa para `qa`.

**Comment by bryant1410** [comment]
Algunas comentadas durante la reunión:

* [x] eliminar pronombres interrogativos (cuándo, quién, etc.)
* [x] eliminar signos de interrogación
* [x] bajar el peso de palabras repetidas
